### ISSUE TITLE
Move to github-pages

### ISSUE THREAD

**Issue by davinov** [jrbeaudoin/devops-metrix#3]
As our app is only client-side, we do not need any server. Maybe it's time to move to GitHub Pages ? It's more reliable that the server we provision quickly during the hackhaton, and will allow us to skip all maintenance tasks.
What do you think @jrbeaudoin @adlenafane ?
It'll be accessible at jrbeaudoin.github.io/devops-metrix, and some CNAME could be put in the repo if we have a domain name in the future.

**Comment by adlenafane** [comment]
Good idea

**Comment by davinov** [comment]
https://github.com/jrbeaudoin/devops-metrix/commit/d40eb3ac288ae950726da5d13ffa270bf81b786d
I pushed to gh-pages and add a `./publish-to-gh-pages.sh`
